name: Pull Request Check

on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Run checks
        run: yarn run check
